### ISSUE TITLE
Questions on Consideration of Evaluating on Val Set

### ISSUE THREAD

**Issue by Song-Jingyu** [TUMFTM/RadarVoxelFusionNet#1]
Hi,

Thanks for presenting this wonderful work to address the fusion problem. After reading the paper carefully I still didn't get the reasons/consideration about not evaluate the performance on test set. Would you mind providing more explanation on this? Thank you!

Best,
Jingyu

**Comment by SuprajaaAnbumozhi** [comment]
Hello,

I have the same question. Why are we not evaluating the performance on test set? It would be nice if I get an answer.
